name: Update Data

on:
  # Triggers the workflow on push events
  push:
  
  # Triggers every 5 minutes
  schedule:
    - cron: "* * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Grab API, parse, and change files to new data
        uses: ThatTimothy/api-grabber@v1.0.0
        with:
          options: "options.json"
      
      - name: Push changes to GitHub
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Data"
          git push
